### ISSUE TITLE
`template-registry` warning `Generated an empty chunk` while rollup

### ISSUE THREAD

**Issue by mkszepp** [adopted-ember-addons/ember-file-upload#1067]
I have seen that there will exported `template-registry` as empty file:

![grafik](https://github.com/adopted-ember-addons/ember-file-upload/assets/19845290/bd65435b-8f7f-4f90-bb8e-48a826e71ebc)

Last test run:
https://github.com/adopted-ember-addons/ember-file-upload/actions/runs/7606502732/job/20712414961#step:4:40

Edit: found this issue on addon blueprint https://github.com/embroider-build/addon-blueprint/issues/195#issuecomment-1735664924

Edit 2: While working on a other addon i have found out, that line is not necessary and generates the empty file. we can remove it:
https://github.com/adopted-ember-addons/ember-file-upload/blob/master/ember-file-upload/rollup.config.mjs#L27

**Comment by gilest** [comment]
Ah nice find. I think you're right.

I was under the impression that only `publicEntrypoints` could be imported by a consuming app. But it doesn't seem to affect the build output except for removing that empty file.

This isn't actually covered by the test suite though – since the template registry is only used by Glint's "loose mode" and the test-app is now in "strict mode". I don't really want to add a whole test app just to cover that 🤔

**Comment by mkszepp** [comment]
Unfortunately I don't have an app that has loose mode active... i have discoverd this only while other addon migration (because in my case the `publiceEntrypoints` were ...
In `ember-page-title` they do not export it in `publicEntrypoint` (the file is only present in declaration folder)...

I have seen that the addon-blueprint brings this line... so maybe this is a bug from blueprint.. i have for now created a issue in addon-blueprint (https://github.com/embroider-build/addon-blueprint/issues/252)
