### ISSUE TITLE
Reset the queue?

### ISSUE THREAD

**Issue by Ramblurr** [adopted-ember-addons/ember-file-upload#18]
After an upload has succeeded or failed, how do you "reset" the component to the default state.

I'm using a modification of the recipe with `multiple=false` and after the file uploads to 100%, the uploader just sits there at 100%.

What's the recommended technique for resetting the `file-queue`?

**Comment by tim-evans** [comment]
I think you'll need to remove the failed item from the queue.

**Comment by tim-evans** [comment]
I may remove failed files from the queue.

**Comment by ashrafhasson** [comment]
Hi @tim-evans ,

I have a similar issue where I'm attempting to remove the file from the queue, say if I manually trigger an action on a customer `photo-field` component to do so, and I don't seem to be able to re-render the `file-upload` component in my `photo-field` component. Maybe this issue is slightly different but I thought the title would appropriately apply to the use case? :)

Btw, I'm using the template example you have in the README.
My component's remove action is like so:
```
  actions: {
    removePhoto(queue) {
      Ember.Logger.log("Files Queued: ", queue.files.length);
      queue.fileQueue.queues[0].files.splice(0, queue.files.length);
      Ember.Logger.log("Files Queued: ", queue.files.length);
      get(this, 'onchange')(null);
      // evt.preventDefault();
      // return false;
    }
  }
```
The `onchange` route-action resets the photo object that's passed to my component, but that doesn't seem to trigger re-rendering `file-upload` part:

```
    queueImageForUpload(file) {
      if (Ember.isPresent(file)) {
        Ember.Logger.log("Create Photo: ", file);
        let photo = this.store.createRecord('photo');
        file.readAsDataURL().then((url) => {
          set(photo, 'url', url);
          set(photo, 'filename', file.name);
          set(photo, 'filesize', file.size);

          set(this.controller, 'customerPhoto', photo);
        });
      } else {
        let photo = get(this.controller, 'customerPhoto');
        set(this.controller, 'customerPhoto', null);
        photo.destroyRecord();

      }
```

Not sure where I'm going wrong but I'm sure there's something missing :D 
Appreciate any help! thanks

**Comment by ashrafhasson** [comment]
I was able to accomplish the above by utilizing the uploader (**file-queue**?) service using [this](https://github.com/tim-evans/ember-file-upload/blob/master/addon/services/file-queue.js#L84-L85) for hint:

```
...
  uploader: Ember.inject.service('file-queue'),
  actions: {
    removePhoto() {
      const uploader = get(this, 'uploader');
      let queue = uploader.find("photos");

      get(queue, 'files').forEach((file) => set(file, 'queue', null));
      set(queue, 'files', Ember.A());

      get(this, 'onchange')(null);
      return false;
    }
  }
```

it would be great if this is highlighted with clarify in the documentation :)

Thanks,

**Comment by tim-evans** [comment]
Sorry about being a bit silent, been busy at work. I'll try to tackle some of this, but some help would be super lovely ❤️

**Comment by jelhan** [comment]
Is this still an issue with latest release? Even on latest master? If so a reproduction would be great. Will close the issue otherwise soon.
