### ISSUE TITLE
How to use the file.blob

### ISSUE THREAD

**Issue by aaronucsd** [adopted-ember-addons/ember-file-upload#413]
Sorry. Not an issue but just curious do I use the `file.blob` like an actual binary? It looks like a meta than an actual blob on inspection. Ay example to display on the HTML page? Thanks.

**Comment by gilest** [comment]
You could try [FileReader.readAsBinaryString](https://adopted-ember-addons.github.io/ember-file-upload/docs/api/modules/ember-file-upload/system/file-reader~FileReader#readAsBinaryString).

Not sure about displaying on the page but perhaps `readAsDataURL` for image display or `readAsText` for text display might be useful.

I'm closing this since it's very old. Let me know if you'd like to reopen.
