### ISSUE TITLE
Regression with surrounding white-space

### ISSUE THREAD

**Issue by nwhittaker** [adopted-ember-addons/ember-file-upload#709]
Given this snippet:

```hbs
Drag and drop a file or <FileUpload>select from your device</FileUpload>.
```

The white-space surrounding the component is rendered differently:

| Version | Rendered | Notes |
| - | - | - |
| 4.0.3 | "Drag and drop a file or select from your device." | Shows the expected behavior. |
| 4.1 and 5.0 betas | "Drag and drop a file or select from your device ." | A space is introduced before the trailing period. |

**Comment by gilest** [comment]
Thank you for reporting this.

The FileUpload component is being deprecated in v5 because it's quite inflexible in terms of DOM/markup. This is a good example of why!

It has been replaced by the `queue.selectFile` modifier which can be applied to a file input. Documentation of this is WIP which is why 5.0 is still in beta.

See [example usage here](https://github.com/adopted-ember-addons/ember-file-upload/blob/master/ember-file-upload/tests/helpers/file-queue-helper-test.js#L84):

```hbs
{{#let (file-queue onFileAdded=this.addFile onFileRemoved=this.removeFile) as |queue|}}
  <label>
    <input type="file" {{queue.selectFile}} hidden>
    Select File
  </label>
{{/let}}
```

**Comment by nwhittaker** [comment]
Thanks for the example. Unfortunately, my project's constraints are such that I was looking for a short-term fix where I could upgrade to v5 but still use the old `FileUpload` component.
