### ISSUE TITLE
Move README.md to package and create linkts for CHANGELOG.md and README.md at repository root

### ISSUE THREAD

**Issue by jelhan** [adopted-ember-addons/ember-file-upload#791]
I noticed that the `CHANGELOG.md` is not at the root of the repository anymore. Instead it at `ember-file-upload/CHANGELOG.md`. This makes it difficult to discover the file and may break autodiscovery by tools like RenovateBot.

There seem to be different patterns regarding location of changelog file in monorepo:

- [ember-auto-import](https://github.com/ef4/ember-auto-import) has `CHANGELOG.md` in the package but additionally has a link at the repository root pointing to the `CHANGELOG.md` in the package.
- [tracked-toolbox](https://github.com/tracked-tools/tracked-toolbox) and [ember.js](https://github.com/emberjs/ember.js) have `CHANGELOG.md` at repository root and not in the package.
- [ember-resources](https://github.com/NullVoxPopuli/ember-resources) has `CHANGELOG.md` in package without a link at repository root. So the same as ember-file-upload currently.

For Ember Auto Import the `CHANGELOG.md` and other files have been moved explicitly to the package in https://github.com/ef4/ember-auto-import/pull/434 by @buschtoens. The argument given there that `README.md`, `CHANGELOG.md` and `LICENSE.md` should be part of the published package makes sense. I would recommend to use the same pattern.

I haven't noticed the issue with `README.md` before. But not having it in the package breaks documentation in package manager listing: https://www.npmjs.com/package/ember-file-upload So I think that one should be addressed as well.

**Comment by gilest** [comment]
> I noticed that the `CHANGELOG.md` is not at the root of the repository anymore. Instead it at `ember-file-upload/CHANGELOG.md`.

That's true. It's because we run `release-it` from within the `ember-file-upload/` dir when releasing so that's where the changelog is written. Maybe it could work with `../CHANGELOG.md`:

https://github.com/adopted-ember-addons/ember-file-upload/blob/2ae82b7c3e7c2704605138c5fa0315cb8bbb6b7b/ember-file-upload/package.json#L138

Perhaps there's a way around this by using `release-it-yarn-workspaces`.

> This makes it difficult to discover the file and may break autodiscovery by tools like RenovateBot.

Not sure about Renovate, but Dependabot uses the GitHub Release objects. Much easier to parse I would guess:

![Screen Shot 2022-05-25 at 11 43 55 AM](https://user-images.githubusercontent.com/36919/170151119-a8c467ff-65e4-47e0-9ff7-91594ac0afbc.png)

> For Ember Auto Import the `CHANGELOG.md` and other files have been moved explicitly to the package in [ef4/ember-auto-import#434](https://github.com/ef4/ember-auto-import/pull/434) by @buschtoens. The argument given there that `README.md`, `CHANGELOG.md` and `LICENSE.md` should be part of the published package makes sense. I would recommend to use the same pattern.

I will make a PR to action this using links. Scoping the doc files to each package makes sense to me. I will create an `ember-file-upload-mirage` package soon so it all needs to be scoped.

> I haven't noticed the issue with `README.md` before. But not having it in the package breaks documentation in package manager listing: https://www.npmjs.com/package/ember-file-upload So I think that one should be addressed as well.

Yes I have seen this and been meaning to remedy anyway.. I should have created an issue 😅
