### ISSUE TITLE
missing dependency breaks app after upgrading to v8.0.0

### ISSUE THREAD

**Issue by stopfstedt** [adopted-ember-addons/ember-file-upload#926]
Hi!

After upgrading to v8.0.0 (from v7.3.0), the file upload functionality ceased to work in my application.

The browser console shows this error:

```
[Uncaught (in promise) Error: Could not find module tracked-built-ins imported from ember-file-upload/helpers/file-queue
```

adding `tracked-build-ins` as a explicit dependency to my `package.json` file appears to overcome this issue (`"tracked-built-ins": "^3.1.1"`), but i doubt that this additional step is intentional. 

I'd appreciate if you had a look at this, thanks!!

**Comment by jelhan** [comment]
`tracked-built-ins` is a peer dependency since v8.0.0: https://github.com/adopted-ember-addons/ember-file-upload/blob/29f601837dc1833380714af61af664bea53ac77f/ember-file-upload/package.json#L112 Having it installed in your app is required. Sadly some package managers are not reporting missing peer dependencies early and clearly.

**Comment by jrjohnson** [comment]
@jelhan this is a thing I really don't understand about how addons are working now. Why is this a "peer" and not just a dependency? Since we consume this in an addon do we also need to make `tracked-built-ins` a peer of our addon so it will be forwarded to the app? Just to be clear I'm fine with this solution to the bug, but I'd really like to understand what the right way to do this stuff is now and I'm not sure where I could even get that info 😢

**Comment by gilest** [comment]
@jrjohnson I'm not certain either. #899 is where we moved those dependencies to peerDeps. I made the assumption that all ember-cli blueprint packages would be reasonable peerDeps... But perhaps not.

At least I think I'll need to add an upgrading guide...

Interested in your thoughts.

**Comment by jrjohnson** [comment]
I didn't realize that `tracked-built-ins` was now in the default blueprint, I guess we haven't caught up to the latest ember-cli. I agree this seems ok to me. I still have a lot of questions about how these work, but reading through those PRs it looks like we all do! I wonder if we should have a "hey how to dependencies work now" meetup at EmberConf or something?

**Comment by gilest** [comment]
One reference you could check @jrjohnson is the[ v2 package format RFC](https://rfcs.emberjs.com/id/0507-embroider-v2-package-format/#peer-dependencies)

>This means that many things addons will try to access from their surrounding environment will need to be listed as peerDependencies. For example, addons that want to import ember-data should list ember-data as a peerDependency, so the app can control the ember-data version and the addon is guaranteed to resolve the same copy.

>This also applies recursively -- if your addon wants to use an addon that needs ember-data, your addon should also list ember-data as a peerDependency. The clearest documented description of how recursive peerDependencies should work is in the [Yarn PnP Formal Guarantees](https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-plug-an-play.md#c-formal-plugnplay-guarantees).

Hopefully this is helpful to you

**Comment by gilest** [comment]
@stopfstedt @jrjohnson any thoughts on the proposed documentation in https://github.com/adopted-ember-addons/ember-file-upload/pull/928?

**Comment by gilest** [comment]
Proposed documentation has been replaced. The [v8 upgrade guide](https://ember-file-upload.pages.dev/docs/upgrade-guide) is now inked from the changelog and GH releases.

**Comment by stopfstedt** [comment]
> @stopfstedt @jrjohnson any thoughts on the proposed documentation in #928?

@gilest - thanks for the upgrade guide. adding `tracked-build-ins` as dev-dependency fixes this issue  for us.
